version: "2.1"
orbs:
  node: circleci/node@5.0.2
jobs:
  test:
    executor:
      name: node/default
    steps:
      - checkout
      - run:
          command: |
            cd user-service
            yarn 
            yarn test
          name: running test
workflows:
  test_my_app:
    jobs:
      - test

      - build-and-test
