version: "2.1"
orbs:
  node: circleci/node@5.0.2
jobs:
  user-service:
    executor:
      name: node/default
    steps:
      - checkout
      - run:
          command: |
            cd user-service
            yarn 
            yarn test
          name: running test
workflows:
  test_my_app:
    jobs:
<<<<<<< HEAD
      - user-service
=======
      - test
>>>>>>> bba4103ff16cad19ff94904d2eca8beefe38a7c9
