---
version: "2.1"
orbs:
  node: circleci/node@5.0.2
  win: circleci/windows@5.0
jobs:
  user-service:
    executor:
      name: node/default
    steps:
      - checkout
      - run:
          command: |
            cd CPHMTOGO/UserService
            yarn 
            yarn test
          name: Running Test
  restaurant-service:
    executor:
      name: node/default
    steps:
      - checkout
      - run:
          command: |
            cd CPHMTOGO/RestaurantService
            yarn 
            yarn test
          name: Running Test
  authentication-service:
    executor:
      name: win/default
    steps:
      - checkout
      - run:
          command: |
            cd CPHMTOGO/AuthenticationService
            dotnet build
          name: Building Solution
      - run:
          command: |
            cd CPHMTOGO/TestZone/AuthenticationServiceTests
            dotnet add package OpenCover --version 4.7.929
          name: Installing OpenCover
      - run:
          command: |
            cd CPHMTOGO/TestZone/AuthenticationServiceTests
            dotnet tool restore
          name: Restoring OpenCover Tool
      - run:
          command: >
            cd CPHMTOGO/TestZone/AuthenticationServiceTests

            opencover -target:"C:\Program Files\dotnet\dotnet.exe" -targetargs:"test --collect:"Code Coverage"" -register:user -output:coverage.xml
          name: Generating Code Coverage Report with OpenCover
      - run:
          command: |
            cd CPHMTOGO/TestZone/AuthenticationServiceTests
            dotnet add package CoberturaConverter --version 2.1.0
          name: Installing CoberturaConverter
      - run:
          command: |
            cd CPHMTOGO/TestZone/AuthenticationServiceTests
            dotnet tool restore
          name: Restoring CoberturaConverter Tool
      - run:
          command: |
            cd CPHMTOGO/TestZone/AuthenticationServiceTests
            coberturaconverter coverage.xml coverage.cobertura.xml
          name: Converting Code Coverage Report to Cobertura Format
      - run:
          command: |
            cd CPHMTOGO/TestZone/AuthenticationServiceTests
            if [ $(grep -c "60.00%" coverage/index.htm) -eq 0 ]; then exit 1; fi
          name: Checking Code Coverage
  order-service:
    executor:
      name: win/default
    steps:
      - checkout
      - run:
          command: |
            cd CPHMTOGO/OrderService
            dotnet build
          name: Building Solution
      - run:
          command: |
            cd CPHMTOGO/TestZone/OrderServiceTests
            dotnet test
          name: Testing Solution
  payment-logging-service:
    executor:
      name: win/default
    steps:
      - checkout
      - run:
          command: |
            cd CPHMTOGO/PaymentLoggingService
            dotnet build
          name: Building Solution
      - run:
          command: |
            cd CPHMTOGO/TestZone/PaymentLoggingServiceTests
            dotnet test
          name: Testing Solution
  payment-service:
    executor:
      name: win/default
    steps:
      - checkout
      - run:
          command: |
            cd CPHMTOGO/PaymentService
            dotnet build
          name: Building Solution
      - run:
          command: |
            cd CPHMTOGO/TestZone/PaymentServiceTests
            dotnet test
          name: Testing Solution
  address-service:
    executor:
      name: win/default
    steps:
      - checkout
      - run:
          command: |
            cd CPHMTOGO/AddressService
            dotnet build
          name: Building Solution
workflows:
  CPHMTOGO_PIPELINE:
    jobs:
      - user-service
      - authentication-service
      - order-service
      - restaurant-service
      - payment-service
      - payment-logging-service
      - address-service
