version: "2.1"
orbs:
  node: circleci/node@5.0.2
  win: circleci/windows@5.0
  codecov: codecov/codecov@3.0.0
jobs:
  user-service:
    executor:
      name: node/default
    steps:
      - checkout
      - run:
          command: |
            cd CPHMTOGO/UserService
            yarn 
            yarn test
          name: Running Test
  restaurant-service:
    executor:
      name: node/default
    steps:
      - checkout
      - run:
          command: |
            cd CPHMTOGO/RestaurantService
            yarn 
            yarn test
          name: Running Test
  authentication-service:
    executor:
      name: win/default
    steps:
      - checkout
      - run:
          command: |
            cd CPHMTOGO/AuthenticationService
            dotnet format
          name: Linting Solution
      - run:
          command: |
            cd CPHMTOGO/AuthenticationService
            dotnet build
          name: Building Solution
      - run:
          command: |
            cd CPHMTOGO/TestZone/AuthenticationServiceTests
            dotnet test /p:CollectCoverage=true /p:CoverletOutputFormat=opencover /p:CoverletOutput=../coverage/coverage.opencover.xml
          name: Testing Solution
      - run:
          command: |
            echo "Uploading Coverage"
            dotnet OpenCover.Console.exe -output:coverage.xml -report:Html coverage.opencover.xml
            dotnet ReportGenerator.dll -reports:coverage.xml -targetdir:coverage-html
          name: Generating report
      - run:
          command: |
            cd coverage-html
            METHOD_COVERAGE=$(grep -oP "(?<=MethodName=\")[^\"]+(?=\")" index.htm | grep 'YOUR_METHOD_NAME' | awk '{print $5}')
            if [ "$METHOD_COVERAGE" -lt "60" ]; then
                echo "Method coverage is less than 60% threshold"
                exit 1
            else
                echo "Method coverage is above 60% threshold"
                exit 0
            fi
          name: Asserting method coverage and Uploading Coverage
  order-service:
    executor:
      name: win/default
    steps:
      - checkout
      - run:
          command: |
            cd CPHMTOGO/OrderService
            dotnet build
          name: Building Solution
      - run:
          command: |
            cd CPHMTOGO/TestZone/OrderServiceTests
            dotnet test
          name: Testing Solution
  payment-logging-service:
    executor:
      name: win/default
    steps:
      - checkout
      - run:
          command: |
            cd CPHMTOGO/PaymentLoggingService
            dotnet build
          name: Building Solution
      - run:
          command: |
            cd CPHMTOGO/TestZone/PaymentLoggingServiceTests
            dotnet test
          name: Testing Solution
  payment-service:
    executor:
      name: win/default
    steps:
      - checkout
      - run:
          command: |
            cd CPHMTOGO/PaymentService
            dotnet build
          name: Building Solution
      - run:
          command: |
            cd CPHMTOGO/TestZone/PaymentServiceTests
            dotnet test
          name: Testing Solution
  address-service:
    executor:
      name: win/default
    steps:
      - checkout
      - run:
          command: |
            cd CPHMTOGO/AddressService
            dotnet build
          name: Building Solution
workflows:
  CPHMTOGO_PIPELINE:
    jobs:
      - user-service
      - authentication-service
      - order-service
      - restaurant-service
      - payment-service
      - payment-logging-service
      - address-service