version: "2.1"
orbs:
  node: circleci/node@5.0.2
  win: circleci/windows@5.0
jobs:
  user-service:
    executor:
      name: node/default
    steps:
      - checkout
      - run:
          command: |
            cd user-service
            yarn 
            yarn test
          name: running test
  authentication-service:
    executor:
      name: win/default
    steps:
      - checkout
      - run:
          command: |
            cd CPHMTOGO\Authentication-Service
            dotnet build
      - run:
          command: |
            cd CPHMTOGO/TestZone/AuthenticationServiceTests
            dotnet test
  order-service:
    executor:
      name: win/default
    steps:
      - checkout
      - run:
          command: |
            cd CPHMTOGO\Order-Service
            dotnet build
      - run:
          command: |
            cd CPHMTOGO/TestZone/OrderServiceTests
            dotnet test
workflows:
  test_my_app:
    jobs:
      - user-service
      - authentication-service
      - order-service
