version: "3"
services:
  loginInfo-db:
    image: postgres
    ports:
      - 3308:5432
    #volumes:
    #  - ./start-script:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_PASSWORD: test123
  payment-db:
    image: postgres
    ports:
      - 3309:5432
    #volumes:
    #  - ./start-script:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_PASSWORD: test123
  address-db:
    image: postgres
    ports:
      - 33010:5432
    #volumes:
    #  - ./start-script:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_PASSWORD: test123
  restaurant-db:
    image: postgres
    ports:
      - 3311:5432
    #volumes:
    #  - ./start-script:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_PASSWORD: test123
  customer-db:
    image: postgres
    ports:
      - 3312:5432
    #volumes:
    #  - ./start-script:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_PASSWORD: test123
  order-db:
    image: postgres
    ports:
      - 3313:5432
    #volumes:
    #  - ./start-script:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_PASSWORD: test123
  employee-db:
    image: postgres
    ports:
      - 3314:5432
    #volumes:
    #  - ./start-script:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_PASSWORD: test123
  company-db:
    image: postgres
    ports:
      - 3315:5432
    #volumes:
    #  - ./start-script:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_PASSWORD: test123
  bonus-db:
    image: postgres
    ports:
      - 3316:5432
    #volumes:
    #  - ./start-script:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_PASSWORD: test123
  