version: "3"
services:
  authentication-db:
    image: postgres
    container_name: 'authentication-db'
    ports:
      - 3308:5432
    volumes:
      - ./init/authentication:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_PASSWORD: test123
  payment-db:
    image: postgres
    ports:
      - 3309:5432
    volumes:
      - ./init/payments:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_PASSWORD: test123
  address-db:
    image: postgres
    ports:
      - 33010:5432
    volumes:
      - ./init/addresses:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_PASSWORD: test123
  restaurant-db:
    image: postgres
    ports:
      - 3311:5432
    volumes:
      - ./init/restaurants:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_PASSWORD: test123
  users-db:
    image: postgres
    ports:
      - 3312:5432
    volumes:
      - ./init/users:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_PASSWORD: test123
  order-db:
    image: postgres
    ports:
      - 3313:5432
    volumes:
      - ./init/orders:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_PASSWORD: test123
  bonus-db:
    image: postgres
    ports:
      - 3316:5432
    volumes:
      - ./init/bonuses:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_PASSWORD: test123
