name: Build Compose

on:
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build compose infrastructure
      run: docker-compose -f infrastructure/docker-compose.infrastructure.dev.yml build
    - name: Build compose applications
      run: docker-compose -f infrastructure/docker-compose.applications.dev.yml build
