name: Workfile-File

on:
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v2
    - name: Build compose Docker
      run: docker-compose -f infrastructure/docker/docker-compose.yml build
##    - name: Build compose applications
##     run: docker-compose -f infrastructure/docker-compose.applications.dev.yml build
